export const homePaths = {
  HOME: "/",
  FAQ: "/faq",
  CONTACT: "/contact",
  PRIVACY_POLICY: "/privacy-policy",
}

export const authPaths = {
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  REGISTER: "/signup",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  EMAIL_VERIFICATION: "/verify-email",
  RETRIEVE: "/retrieve",
  APPLY: "/application",
}

export const users = {
  DASHBOARD: "/dashboard",
  AGENTS: "/agents",
  AGENTS_DETAILS: "/agents/:id",
  SUPERAGENTS: "/superagents",
  SUPERAGENTS_DETAILS: "/superagents/:id",
  Driver: "/Driver",
  Driver_DETAILS: "/Driver/:id",
  Driver_REGISTER: "/Driver/Register",
  CLAIMS: "/claims",
  CLAIMS_DETAILS: "/claims/:id",
  CUSTOMERS: "/customers",
  CUSTOMERS_DETAILS: "/customers/:id",
  SERVICEPROVIDERS: "/serviceproviders",
  SERVICEPROVIDERS_DETAILS: "/serviceproviders/:id",
  NOTIFICATIONS: "/notifications",
  TRANSACTIONS: "/transactions",
  SETTINGS: "/settings",
  PROFILE: "/profile",
  KYCFORM: "/kycform",
  PAYMENTS: "/payments",
}

export const agents = {
  DASHBOARD: "/dashboard",
  AGENTS: "/agents",
  AGENTS_DETAILS: "/agents/:id",
  SUPERAGENTS: "/superagents",
  SUPERAGENTS_DETAILS: "/superagents/:id",
  Driver: "/Driver",
  Driver_DETAILS: "/Driver/:id",
  Driver_REGISTER: "/Driver/Register",
  CLAIMS: "/claims",
  CLAIMS_DETAILS: "/claims/:id",
  VERIFYPAYMENT: "/payment/verify",
  CUSTOMERS: "/customers",
  CUSTOMERS_DETAILS: "/customers/:id",
  SERVICEPROVIDERS: "/serviceproviders",
  SERVICEPROVIDERS_DETAILS: "/serviceproviders/:id",
  NOTIFICATIONS: "/notifications",
  TRANSACTIONS: "/transactions",
  SETTINGS: "/settings",
  PROFILE: "/profile",
  KYCFORM: "/kycform",
  PAYMENTS: "/payments",
}

export const Admin = {
  DASHBOARD: "/dashboard",
  APPLICATION: "/Applications",
  APPLICATION_DETAILS: "/applications/:id",
  AGENTS: "/agents",
  AGENTS_DETAILS: "/agents/:id",
  SUPERAGENTS: "/superagents",
  SUPERAGENTS_DETAILS: "/superagents/:id",
  Driver: "/Driver",
  Driver_DETAILS: "/Driver/:id",
  Driver_REGISTER: "/Driver/Register",
  Driver_VWO: "/PropertiesVWO",
  Driver_VNO: "/PropertiesVNO",
  Charges: "/charges",
  CLAIMS: "/claims",
  CLAIMS_DETAILS: "/claims/:id",
  CUSTOMERS: "/customers",
  CUSTOMERS_DETAILS: "/customers/:id",
  SERVICEPROVIDERS: "/serviceproviders",
  SERVICEPROVIDERS_DETAILS: "/serviceproviders/:id",
  NOTIFICATIONS: "/notifications",
  TRANSACTIONS: "/transactions",
  SETTINGS: "/settings",
  PROFILE: "/profile",
  KYCFORM: "/kycform",
  PAYMENTS: "/payments",
}
